version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: yarn run build:basic
      - run: yarn run bootstrap
      - run: yarn run lint

      - run:
          command: |
            if [ $CIRCLE_BRANCH = "master" ] ; then
              yarn run coverage
            fi

  publish:
    docker:
      - image: circleci/node:10.13

    working_directory: ~/repo

    steps:
      - checkout

      - add-ssh-keys:
          fingerprints:
            - $FINGER_PRINT

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - packages/vue-flagify/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run build:basic
      - run: yarn run bootstrap
      - run: yarn run build:vue

      - run: git config --global user.email "$EMAIL"
      - run: git config --global user.name "$USER_NAME"
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: ./node_modules/.bin/lerna --cd-version="patch" --yes --registry="https://registry.npmjs.org/" publish

workflows:
  version: 2
  test_and_staging:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
